[package]
name = "proteus"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.4"
aws-sdk-bedrock = "1.39.0"
aws-sdk-bedrockruntime = "1.42.0"
axum = "0.7.5"
serde_json = "1.0.121"
tokio = { version = "1.39.2", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
